
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umashankar
 */
public class pap_match extends javax.swing.JFrame {
String p,n;
    /**
     * Creates new form pap_match
     */
    public pap_match() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        tf4 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child_id", "PAP_id", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 660, 113));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Enter Child_id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 220, 50));
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 320, 38));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Enter Parent_id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 280, 58));
        jPanel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 310, 38));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 150, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("Show matches");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 180, 50));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("Back to homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 760, 230, 50));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PAP_id", "Name", "Age", "Total Income"
            }
        ));
        tb1.setOpaque(false);
        jScrollPane2.setViewportView(tb1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 650, 120));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("Update status");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 760, 170, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Confirmation:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 674, 310, 40));

        rb1.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        rb1.setText("Yes");
        rb1.setOpaque(false);
        jPanel1.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 90, -1));

        tf4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, 150));

        rb2.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        rb2.setText("No");
        rb2.setOpaque(false);
        jPanel1.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Umashankar\\Pictures\\Abhigrith\\1469547938-adopting-forever-family.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 1310, 823));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        try{
            n = tf2.getText();
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost/abhigrith","root","giis");
            Statement smt = con.createStatement();
            String query = "select * from pap_info where pap_id = "+n+";" ;
            ResultSet rs = smt.executeQuery(query);

            while(rs.next()){
                String pap_id = rs.getString("pap_id");
                String name = rs.getString("name");
                String age = rs.getString("age");
                int income = rs.getInt("Total_Income");
                model.addRow(new Object[] {pap_id,name,age,income});                
                
            }
            rs.close();
            smt.close();
            con.close();

        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel model= (DefaultTableModel) tb.getModel();
        try{
             p = tf1.getText();
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost/Abhigrith","root","giis");
            Statement smt = con.createStatement();
            String query = "select * from matching_id where child_id = "+p+";" ;
            ResultSet rs = smt.executeQuery(query);

            while(rs.next()){
                String pap_id = rs.getString("pap_id");
                String child_id = rs.getString("child_id");
                String status = rs.getString("confirm");
                model.addRow(new Object[] {child_id,pap_id,status});
                
            }
            
         
        String query2 = "select * from child_info where child_id = "+p+";" ;
        ResultSet rs1 = smt.executeQuery(query2);
        
        while(rs1.next()){
        String photo = rs1.getString("photo_path");
            
        ImageIcon image = new ImageIcon(photo);
        Image im = image.getImage();
        Image myImg = im.getScaledInstance(tf4.getWidth(),tf4.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        
        tf4.setIcon(newImage);
        }
        

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        warden_homepage frame = new warden_homepage();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        DefaultTableModel model= (DefaultTableModel) tb.getModel();
        try{
            String confirm=null;
        
        if (rb1.isSelected()==true){
            confirm="YES";}
        if (rb2.isSelected()==true){
            confirm = "NO";}
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/Abhigrith","root","giis");
        Statement smt = con.createStatement();
        String query = "Update matching_id set confirm = '"+confirm+"' where child_id='"+p+"' and pap_id = '"+n+"';";  
        smt.executeUpdate(query);
        System.out.print(confirm);
            
        smt.close();
        con.close();
        JOptionPane.showMessageDialog(null, "Status Update was successful");

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pap_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pap_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pap_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pap_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pap_match().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTable tb;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JLabel tf4;
    // End of variables declaration//GEN-END:variables
}
